services:
    newscoop_newscoop.routing.loader.plugins:
        class: Newscoop\NewscoopBundle\Routing\PluginsLoader
        arguments: ["@newscoop.plugins.manager", "@service_container"]
        tags:
            - { name: routing.loader }

    newscoop_newscoop.doctrine.event_dispatcher_proxy:
        class: Newscoop\Doctrine\EventDispatcherProxy
        arguments: ["@event_dispatcher"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    newscoop_newscoop.menu_builder:
        class: Newscoop\NewscoopBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@service_container"]

    newscoop_newscoop.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: newscoop_newscoop.menu_builder
        factory_method: mainMenu
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    newscoop_newscoop.menu.breadcrumb:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: newscoop_newscoop.menu_builder
        factory_method: mainBreadcrumb
        tags:
            - { name: knp_menu.menu, alias: breadcrumb } # The alias is what is used to retrieve the menu

    newscoop_newscoop.twig.newscoop_extension:
        class: Newscoop\NewscoopBundle\Twig\NewscoopExtension
        arguments: 
            - @service_container
        tags:
            - { name: twig.extension }

    newscoop_newscoop.password_encoder:
        class: Newscoop\NewscoopBundle\Security\Encoder\NewscoopPasswordEncoder

    newscoop_newscoop.security.authentication.success_handler:
        class: %newscoop_newscoop.security.authentication.success_handler.class%
        public: false
        arguments:  ['@security.http_utils', {}, '@auth.adapter']

parameters:
    smarty.extension.routing.class: "Newscoop\\NewscoopBundle\\Extension\\RoutingExtension"
    newscoop_newscoop.security.authentication.success_handler.class: "Newscoop\\NewscoopBundle\\Security\\Http\\Authentication\\AuthenticationSuccessHandler"
    security.authentication.failure_handler.class: "Newscoop\\NewscoopBundle\\Security\\Http\\Authentication\\AuthenticationFailedHandler"
    security.logout.success_handler.class: "Newscoop\\NewscoopBundle\\Security\\Http\\Authentication\\LogoutSuccessHandler"
    security.authentication.listener.form.class: "Newscoop\\NewscoopBundle\\EventListener\\CaptchaUsernamePasswordFormAuthenticationListener"