<?php if (empty($this->rules) && empty($this->rulesParents)) {
    echo $this->renderMessage(getGS('No rules.'));
    return;
} ?>

<?php foreach ($this->resources as $resource => $name) {
    if (empty($this->rules[$resource]) && empty($this->rulesParents[$resource])) { // ignore empty
        continue;
    }
?>
<dl class="resource">
    <dt><?php echo $name; ?></dt>

    <?php
    if (!isset($this->rulesParents[$resource])) {
        $this->rulesParents[$resource] = array();
    }

    foreach ($this->rulesParents[$resource] as $rule) { ?>
    <dd class="<?php echo $rule->class; ?><?php echo $this->canManage ? ' inherited' : ''; ?>"><strong><?php echo $rule->type; ?></strong> <?php echo $rule->action ?: getGS('Any action'); ?></dd>
    <?php } ?>

    <?php foreach ((array) $this->rules[$resource] as $rule) { ?>
    <dd class="<?php echo $rule->class; ?>">
        <?php if ($this->canManage) { ?>
        <a class="delete icon" href="<?php echo $this->url(array(
            'controller' => 'acl',
            'action' => 'delete',
            'rule' => $rule->id,
        )); ?>" title="<?php putGS('Remove rule'); ?>"><?php putGS('Remove'); ?></a>
        <?php } ?>
        <strong><?php echo $rule->type; ?></strong> <?php echo $rule->action ?: getGS('Any action'); ?>
    </dd>
    <?php } ?>
</dl>
<?php } ?>
