<?php
$headStyle = $this->headLink();
$headStyle->appendStylesheet($this->baseUrl('/admin-style/notices.css'));
?>
<?php $this->placeholder('title')->captureStart(); ?>
<?php putGS('Manage notice categories'); ?>
<?php $this->placeholder('title')->captureEnd(); ?>
<div id="noticeCategories">

<?php foreach ($this->Trees as $slug => $tree): ?>
    <fieldset>
        <legend><?php echo $tree['root']->getTitle() ?>             <a href="#">x</a>
        </legend>
        <ul>

    <?php foreach ($tree['children'] as $leaf): ?>
            <li><?php echo $leaf->getTitle()?>
            <a href="#">edit</a>
                <a href="#">x</a>
            </li>
        <?php endforeach; ?>
        </ul>
        </fieldset>
    <?php endforeach;?>
</div>



<?php print_r($this->result); ?>
<?php echo $this->categoryForm; ?>