Newscoop\Package\Item:
    exclusion_policy: ALL
    properties:
        caption:
            expose: true
            read_only: true
            type: string
            groups: ["details"]
            serialized_name: caption
        type:
            expose: true
            read_only: true
            type: string
            access_type: public_method
            groups: ["details"]
            serialized_name: type
        link:
            expose: true
            read_only: true
            type: image_uri
            groups: ["details"]
            accessor:
                getter: getItem
            serialized_name: link