Newscoop\Entity\Section:
    exclusion_policy: ALL
    properties:
        number:
            expose: true
            read_only: true
            type: integer
            groups: ["list", "details"]
            serialized_name: number
        name:
            expose: true
            read_only: true
            type: string
            groups: ["list", "details"]
            serialized_name: title
        publication:
            expose: true
            read_only: true
            type: string
            groups: ["details"]
            accessor:
                getter: getPublicationName
            serialized_name: publicationName
            since_version: 1.1
        issue:
            expose: true
            read_only: true
            type: string
            groups: ["details"]
            accessor:
                getter: getIssueName
            serialized_name: issueName
            since_version: 1.1