<?php $this->placeholder('title')
->set(getGS('Edit User Type: $1', $this->group)); ?>

<?php echo $this->action('list', 'acl', 'admin', array(
    'role' => $this->group->getRoleId(),
    'next' => $this->url(),
)); ?>

<?php $this->sidebar(getGS('Add rule'), $this->action('edit', 'acl', 'admin', array(
    'role' => $this->group->getRoleId(),
    'next' => $this->url(),
))); ?>

<?php $this->sidebar(getGS('Rename User Type'), $this->action('edit-name', 'user-group', 'admin', array(
    'group' => $this->group->getId(),
))); ?>
