<?php $this->placeholder('title')->set($this->translator->trans('User types')); ?>

<?php
if (empty($this->groups)) {
    $this->renderMessage($this->translator->trans('No user types.'));
    return;
}
?>

<ul class="edit user-types">
    <?php foreach ($this->groups as $group) { ?>
    <li>
        <a class="icon delete confirm" href="<?php echo $this->url(array(
            'action' => 'delete',
            'group' => $group->getId(),
        )); ?>" title="<?php putGS('Delete user type $1', $this->escape($group->getName())); ?>"><?php putGS('Delete'); ?></a>
        <a class="edit" href="<?php echo $this->url(array(
            'action' => 'edit-access',
            'group' => $group->getId(),
        )); ?>" title="<?php putGS('Edit user type $1', $this->escape($group->getName())); ?>"><?php echo $this->escape($group->getName()); ?></a>
    </li>
    <?php } ?>
</ul>
