services:
    comment:
        class:      Newscoop\Services\CommentService
        arguments:  ["@em", "@newscoop.publication_service"]
        tags:
            -  { name: kernel.event_listener, event: comment.create, method: update }
            -  { name: kernel.event_listener, event: comment.update, method: update }
            -  { name: kernel.event_listener, event: comment.recommended, method: update }
            -  { name: kernel.event_listener, event: comment.delete, method: update }