admin_login:
    pattern:   /admin/login
    defaults:  { _controller: NewscoopNewscoopBundle:Security:login }
admin_login_check:
    pattern:   /admin/login_check
admin_logout:
    pattern:   /admin/logout{php}
    defaults: { php: ".php" }
fos_js_routing:
    prefix: /admin
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
_bazinga_exposetranslation:
    prefix: /admin
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
gimme:
    type: rest
    prefix: /api
    resource: "@NewscoopGimmeBundle/Resources/config/routing.yml"
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation/rest-api
NewscoopGimmeBundleConfigureApi:
    resource: "@NewscoopGimmeBundle/Controller/ConfigureApiController.php"
    prefix:   /
    type:     annotation
newscoop:
    prefix: /
    resource: "@NewscoopNewscoopBundle/Resources/config/routing.yml"
plugins:
    resource: .
    type: plugins
zendBridge:
    prefix: /
    resource: "@NewscoopZendBridgeBundle/Resources/config/routing.yml"